#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=LED_NBA_Dataset
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=12:00:00
#SBATCH --output=Original_LED_%A.out


source activate led
module purge
module load 2022
module load CUDA/11.7.0

cd $HOME/thesis/LED/
python main_led_nba.py --cfg led_augment --info original_nba --dataset nba


# past_frames                  : 10
# future_frames                : 20