#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=2D_MultiSpires
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --time=00:45:00
#SBATCH --output=5_5_MultiSpires_2D_output_%A.out


source activate led
module purge
module load 2022
module load CUDA/11.7.0

cd $HOME/MoTric/5_LED_Kitti_BetterCheckpoints/
python main_led_nba.py --cfg 5_5_MultiSpires_2D --info 5_5_MultiSpires_2D --dataset spires


